/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myProject481;

import java.util.ArrayList;

public class App {
    public static boolean search(ArrayList<Integer> array, int e) {
        System.out.println("inside search");
        if (array == null) return false;
  
        for (int elt : array) {
          if (elt == e) return true;
        }
        return false;
      }

    public static void main(String[] args) {
        //App p = new App();
        ArrayList<Integer> l = new ArrayList<Integer>();
        l.add(5);
        l.add(4);
        l.add(6);
        l.add(10);
        boolean b = search(l, 4);
        System.out.println(b);
    
    }
}
